/**
 * Traductions du site : pour chaque phrase française de la page, son anglais (en) et son
 * chinois (zh). Une phrase absente, ou sans traduction dans une langue, reste en français.
 * La clé est la phrase française exacte, espaces multiples ramenés à un seul : si vous
 * modifiez une phrase dans index.html, script.js ou js/header-templates.js, modifiez aussi
 * sa clé ici. Les titres venus du site photo (sélection, séries, galeries) y figurent aussi.
 */
window.TRADUCTIONS = {
    // Navigation et interface
    "Chargement...": { en: "Loading…", zh: "加载中…" },
    "KF’, retour en haut de page": { en: "KF’, back to top", zh: "KF’，返回页首" },
    "Menu": { zh: "菜单" },
    "À propos": { en: "About", zh: "关于" },
    "Portfolio": { zh: "作品集" },
    "Graphisme": { en: "Graphic design", zh: "平面设计" },
    "Photographie": { en: "Photography", zh: "摄影" },
    "Mes livres": { en: "My books", zh: "我的书" },
    "Une expertise auctoriale": { en: "Authorship research", zh: "作者研究" },
    "Contact": { zh: "联系" },
    "Changer de langue": { en: "Change language", zh: "切换语言" },
    "Fermer": { en: "Close", zh: "关闭" },
    "Précédent": { en: "Previous", zh: "上一张" },
    "Suivant": { en: "Next", zh: "下一张" },
    "Karl Forterre | Auteur": { en: "Karl Forterre | Author", zh: "Karl Forterre | 作家" },

    // En-tête
    "Auteur": { en: "Author", zh: "作家" },
    "Les belles lettres font les bons mots.": { en: "Fine letters make fine words.", zh: "美文成就妙语。" },
    "« Les belles lettres font les bons mots. »": { en: "“Fine letters make fine words.”", zh: "“美文成就妙语。”" },
    "Découvrir mes œuvres": { en: "Discover my works", zh: "探索我的作品" },
    "Découvrir mes écrits": { en: "Discover my writing", zh: "探索我的文字" },
    "Me contacter": { en: "Contact me", zh: "联系我" },
    "Mes œuvres": { en: "My works", zh: "我的作品" },
    "Défiler": { en: "Scroll", zh: "向下滚动" },
    "Portrait de Karl Forterre, auteur": { en: "Portrait of Karl Forterre, author", zh: "作家 Karl Forterre 的肖像" },
    "Portrait de Karl Forterre": { en: "Portrait of Karl Forterre", zh: "Karl Forterre 的肖像" },
    "Nouvelles": { en: "Short stories", zh: "短篇小说" },
    "Poésie": { en: "Poetry", zh: "诗歌" },

    // À propos
    "L'auteur derrière les mots": { en: "The author behind the words", zh: "文字背后的作者" },
    "Passionné par le pouvoir des mots et la beauté de la langue française, je consacre ma plume à créer des œuvres qui résonnent avec l'âme de mes lecteurs.": { en: "Passionate about the power of words and the beauty of the French language, I devote my pen to creating works that resonate with my readers’ souls.", zh: "我热爱文字的力量与法语之美，致力于用笔创作能与读者心灵共鸣的作品。" },
    "Mon parcours m'a mené à explorer différentes formes d'écriture, de la fiction littéraire à la rédaction professionnelle, toujours avec le même souci du détail et de l'élégance stylistique.": { en: "My path has led me to explore many forms of writing, from literary fiction to professional writing, always with the same care for detail and stylistic elegance.", zh: "我的经历让我探索了多种写作形式，从文学创作到专业写作，始终秉持对细节与文体之美的追求。" },
    "Chaque projet est une nouvelle aventure, une occasion de donner vie à des idées et de tisser des récits qui marquent les esprits.": { en: "Every project is a new adventure, a chance to bring ideas to life and to weave stories that leave a lasting impression.", zh: "每个项目都是一次新的冒险，是让想法成真、编织动人故事的契机。" },
    "Ouvrages publiés": { en: "Published works", zh: "出版作品" },
    "Projets réalisés": { en: "Completed projects", zh: "完成项目" },
    "Années d'expérience": { en: "Years of experience", zh: "年经验" },

    // Portfolio
    "Créations": { en: "Creations", zh: "创作" },
    "Une sélection de mes créations visuelles et artistiques.": { en: "A selection of my visual and artistic creations.", zh: "我的视觉与艺术创作精选。" },
    "Voir mes réalisations graphiques": { en: "See my graphic design work", zh: "查看我的平面设计作品" },
    "Portrait Éclaté": { en: "Shattered Portrait", zh: "碎裂的肖像" },
    "Exploration artistique de la fragmentation identitaire": { en: "An artistic exploration of fragmented identity", zh: "对身份碎片化的艺术探索" },
    "Le Plan": { zh: "《Le Plan》" },
    "Affiche cinématographique": { en: "Film poster", zh: "电影海报" },
    "Sphère": { en: "Sphere", zh: "球体" },
    "Abstraction géométrique": { en: "Geometric abstraction", zh: "几何抽象" },
    "Pochette": { en: "Record Sleeve", zh: "唱片封套" },
    "Design de pochette musicale": { en: "Album cover design", zh: "音乐专辑封面设计" },
    "Street Color": { zh: "街头色彩" },
    "Explosion de couleurs urbaines": { en: "An explosion of urban colours", zh: "城市色彩的迸发" },
    "Harpe Délire": { en: "Harp Delirium", zh: "竖琴狂想" },
    "Vision onirique musicale": { en: "A dreamlike musical vision", zh: "梦幻般的音乐意象" },
    "Gouttelette": { en: "Droplet", zh: "水滴" },
    "L'infiniment petit capturé": { en: "The infinitely small, captured", zh: "定格微观世界" },
    "Révolution": { en: "Revolution", zh: "革命" },
    "Affiche engagée": { en: "A committed poster", zh: "有态度的海报" },
    "Danseur": { en: "Dancer", zh: "舞者" },
    "Capture du mouvement": { en: "Capturing movement", zh: "捕捉动感" },
    "Route Mystique": { en: "Mystic Road", zh: "神秘之路" },
    "Voyage vers l'inconnu": { en: "A journey into the unknown", zh: "驶向未知的旅程" },
    "Cosmos": { zh: "宇宙" },
    "L'infini à portée de main": { en: "Infinity within reach", zh: "触手可及的无限" },
    "Bateau Spatial": { en: "Space Ship", zh: "太空之船" },
    "Concept art futuriste": { en: "Futuristic concept art", zh: "未来主义概念艺术" },
    "Vanité": { en: "Vanitas", zh: "虚空静物" },
    "Réflexion sur l'éphémère": { en: "A reflection on the ephemeral", zh: "对短暂的沉思" },
    "Ninja": { zh: "忍者" },
    "Mystère et ombre": { en: "Mystery and shadow", zh: "神秘与阴影" },
    "Été d'Amour": { en: "Summer of Love", zh: "爱之夏" },
    "Composition estivale romantique": { en: "A romantic summer composition", zh: "浪漫的夏日构图" },
    "Pétrole et Rêves": { en: "Oil and Dreams", zh: "石油与梦想" },
    "Vision industrielle onirique": { en: "A dreamlike industrial vision", zh: "梦幻般的工业景象" },
    "Citrouillesque": { en: "Pumpkinesque", zh: "南瓜奇想" },
    "Art d'automne fantaisiste": { en: "Whimsical autumn art", zh: "奇趣秋日艺术" },
    "DJ Transparent": { en: "Transparent DJ", zh: "透明 DJ" },
    "Art musical contemporain": { en: "Contemporary music art", zh: "当代音乐艺术" },
    "Time Machine": { zh: "时光机" },
    "Voyage temporel visuel": { en: "A visual journey through time", zh: "视觉时光之旅" },
    "Potentiel": { en: "Potential", zh: "潜能" },
    "Expression abstraite du possible": { en: "An abstract expression of the possible", zh: "对可能性的抽象表达" },
    "Bibliothèque": { en: "Library", zh: "图书馆" },
    "Univers littéraire visuel": { en: "A visual literary universe", zh: "视觉化的文学世界" },
    "Cookie": { zh: "饼干" },
    "Art gourmand": { en: "Delicious art", zh: "美味艺术" },
    "Boule": { en: "Orb", zh: "圆球" },
    "Géométrie parfaite": { en: "Perfect geometry", zh: "完美几何" },
    "Fonderie": { en: "Foundry", zh: "铸造厂" },
    "Ambiance industrielle": { en: "An industrial atmosphere", zh: "工业氛围" },
    "Remerciement": { en: "Thank You", zh: "致谢" },
    "Expression de gratitude visuelle": { en: "A visual expression of gratitude", zh: "以视觉表达感激" },

    // Graphisme
    "Réalisations": { en: "Work", zh: "作品" },
    "Graphisme et édition": { en: "Graphic design and publishing", zh: "平面设计与出版" },
    "Logos, couvertures, affiches et publicités, pour des maisons d’édition, des événements et des projets universitaires.": { en: "Logos, book covers, posters and advertisements for publishers, events and university projects.", zh: "为出版社、活动和大学项目设计的标志、封面、海报与广告。" },
    "Vue d’ensemble": { en: "Overview", zh: "总览" },
    "Défilement": { en: "Scroll view", zh: "滚动浏览" },
    "Œuvres précédentes": { en: "Previous works", zh: "上一组作品" },
    "Œuvres suivantes": { en: "Next works", zh: "下一组作品" },
    "Société des Éditions du Poitou": { zh: "普瓦图出版社" },
    "Voici le logo que j’ai réalisé pour la Société des Éditions du Poitou. Ce logo est suivi de publicités ainsi que de documents à usage interne. Sont également présentes les couvertures que j’ai pu réaliser pour la maison d’édition pictavienne.": { en: "Here is the logo I designed for the Société des Éditions du Poitou, followed by advertisements and internal documents. Also shown are the covers I created for this publishing house based in Poitiers.", zh: "这是我为普瓦图出版社设计的标志，随后是广告和内部文件，以及我为这家位于普瓦捷的出版社设计的书籍封面。" },
    "Logo de la Société des Éditions du Poitou": { en: "Logo of the Société des Éditions du Poitou", zh: "普瓦图出版社标志" },
    "Présentation du logo": { en: "Logo presentation", zh: "标志说明" },
    "Carte de la maison d’édition": { en: "The publisher’s card", zh: "出版社名片" },
    "Publicité « Une infinité d’impressions possibles »": { en: "Advertisement: “Endless printing possibilities”", zh: "广告：“无限印刷可能”" },
    "Publicité « On voit la vie en couleur »": { en: "Advertisement: “We see life in colour”", zh: "广告：“我们眼中的生活是彩色的”" },
    "Publicité « Engagées »": { en: "Advertisement: “Engagées” (committed prints)", zh: "广告：“Engagées”（有立场的印刷品）" },
    "Publicité « Des impressions pour l’année »": { en: "Advertisement: “Prints for the whole year”", zh: "广告：“全年印刷”" },
    "Publicité « Nos luttes sous reliure »": { en: "Advertisement: “Our struggles, bound”", zh: "广告：“装订我们的斗争”" },
    "Couverture de « Kolo », de Léo Tamisier": { en: "Cover of “Kolo” by Léo Tamisier", zh: "Léo Tamisier《Kolo》封面" },
    "Couverture de « L’histoire du petit Théo »": { en: "Cover of “L’histoire du petit Théo”", zh: "《小泰奥的故事》封面" },
    "Couverture de « Darshan »": { en: "Cover of “Darshan”", zh: "《Darshan》封面" },
    "Quatrième de couverture de « Darshan »": { en: "Back cover of “Darshan”", zh: "《Darshan》封底" },
    "Collection Cheminement": { en: "The Cheminement collection", zh: "Cheminement 丛书" },
    "Cheminement est une collection de la Société des Éditions du Poitou. Ce logo induit le dynamisme par son triangle qui forme un petit marque-page rouge dont la couleur rappelle l’engagement social de la maison d’édition.": { en: "Cheminement is a collection of the Société des Éditions du Poitou. Its logo suggests momentum through its triangle, which forms a small red bookmark whose colour recalls the publisher’s social commitment.", zh: "Cheminement 是普瓦图出版社的一个丛书系列。标志中的三角形构成一枚红色小书签，富有动感，红色象征出版社的社会担当。" },
    "Logo de la collection Cheminement": { en: "Logo of the Cheminement collection", zh: "Cheminement 丛书标志" },
    "Il s’agit d’un document de promotion du F-Tournament dont la création des visuels de communication m’a été confiée. Cet événement e-sport encourageait au don de moelle osseuse. Il a été lauréat du prix Solidarité de l’université de Poitiers pour l’année 2021.": { en: "A promotional document for the F-Tournament, whose communication visuals I was entrusted with. This e-sports event encouraged bone marrow donation and won the University of Poitiers Solidarity Prize in 2021.", zh: "这是 F-Tournament 的宣传资料，其视觉传播设计由我负责。这项电子竞技活动倡导骨髓捐献，并荣获普瓦捷大学 2021 年度团结奖。" },
    "Visuel du F-Tournament": { en: "F-Tournament visual", zh: "F-Tournament 视觉设计" },
    "Dans le cadre de travaux universitaires, ce photomontage a pu être réalisé sur la base du montage d’après photo de Nicolas Boudier « Artefact » de Joris Mathieu.": { en: "Created as part of university coursework, this photomontage is based on Nicolas Boudier’s photograph for Joris Mathieu’s “Artefact”.", zh: "这幅照片蒙太奇是大学课业作品，基于 Nicolas Boudier 为 Joris Mathieu 的《Artefact》拍摄的照片创作。" },
    "Photomontage « Artefact »": { en: "“Artefact” photomontage", zh: "照片蒙太奇《Artefact》" },
    "Voici deux affiches destinées à accompagner un court métrage réalisé par Pierre Jeandroz pour le festival de Troyes. Ces affiches portent une œuvre humoristique, au ton léger.": { en: "Two posters for a short film directed by Pierre Jeandroz for the Troyes festival: a humorous work with a light touch.", zh: "为 Pierre Jeandroz 执导、参加特鲁瓦电影节的短片设计的两张海报。这是一部轻松幽默的作品。" },
    "Affiche du court métrage « Le Plan »": { en: "Poster for the short film “Le Plan”", zh: "短片《Le Plan》海报" },
    "Seconde affiche du court métrage « Le Plan »": { en: "Second poster for the short film “Le Plan”", zh: "短片《Le Plan》第二张海报" },
    "Une police de caractères": { en: "A typeface", zh: "一款字体" },
    "Mon intérêt pour les différentes polices et le travail de certains fondeurs m’a amené à mener l’expérience de proposer une police et les fontes associées.": { en: "My interest in typefaces and in the work of certain type foundries led me to try designing a typeface and its associated fonts.", zh: "出于对各种字体以及一些字体设计工坊作品的兴趣，我尝试设计了一款字体及其配套字型。" },
    "Spécimen de la police": { en: "Type specimen", zh: "字体样张" },
    "Spécimen : « Portez ce whisky au vieux juge blond qui fume »": { en: "Specimen: “Portez ce whisky au vieux juge blond qui fume” (a French pangram)", zh: "样张：“Portez ce whisky au vieux juge blond qui fume”（法语全字母句）" },
    "Couvertures, logos et supports": { en: "Covers, logos and materials", zh: "封面、标志与各类物料" },
    "J’ai eu la chance de produire des visuels pour différents usages et contextes. Ceux-ci incluent un grand nombre de couvertures, mais également des supports thérapeutiques ainsi que des outils pour des animations ou de communication dans des structures.": { en: "I have had the chance to create visuals for many uses and settings: a large number of book covers, but also therapeutic materials and tools for activities and communication in various organisations.", zh: "我有幸为不同用途和场合创作视觉作品：大量书籍封面，还有治疗辅助材料，以及用于各类机构活动与宣传的工具。" },
    "Couverture de « Bavardage philosophique d’un citoyen ordinaire »": { en: "Cover of “Bavardage philosophique d’un citoyen ordinaire”", zh: "《一位普通公民的哲学闲谈》封面" },
    "Matériel orthophonique": { en: "Speech therapy material", zh: "语言治疗教具" },
    "Logo « Reverse »": { en: "“Reverse” logo", zh: "“Reverse”标志" },
    "Logo « SOS Cookies »": { en: "“SOS Cookies” logo", zh: "“SOS Cookies”标志" },
    "Logo « Ma priorité ! »": { en: "“Ma priorité !” logo", zh: "“Ma priorité !”标志" },
    "Affiche « Lire, plus qu’un loisir »": { en: "Poster: “Reading, more than a pastime”", zh: "海报：“阅读，不只是消遣”" },
    "Affiche « Rêvons, imaginons »": { en: "Poster: “Let’s dream, let’s imagine”", zh: "海报：“让我们梦想，让我们想象”" },
    "Affiche « Simple »": { en: "Poster: “Simple”", zh: "海报：“Simple”" },

    // Photographie
    "Galerie photo": { en: "Photo gallery", zh: "摄影作品" },
    "Captures d'instants, jeux de lumière et perspectives uniques.": { en: "Captured moments, plays of light and unique perspectives.", zh: "定格瞬间、光影变幻与独特视角。" },
    "Voir la photo": { en: "View the photo", zh: "查看照片" },
    "Toutes mes photos": { en: "All my photos", zh: "我的全部照片" },
    "Photos de Karl Forterre, libres de droits sur": { en: "Photos by Karl Forterre, royalty-free on", zh: "Karl Forterre 的照片，免版税发布于" },
    "Photo précédente": { en: "Previous photo", zh: "上一张照片" },
    "Photo suivante": { en: "Next photo", zh: "下一张照片" },
    "Auto": { zh: "自动" },
    "Série :": { en: "Series:", zh: "系列：" },
    "Galerie :": { en: "Gallery:", zh: "图集：" },
    "Croissant de lune au crépuscule": { en: "Crescent moon at dusk", zh: "暮色中的新月" },
    "Un fin croissant de lune dans le dégradé du soir.": { en: "A thin crescent moon in the evening gradient.", zh: "傍晚渐变天色中的一弯新月。" },
    "Ciel étoilé": { en: "Starry sky", zh: "星空" },
    "Un ciel sombre semé d'étoiles, traversé par la Voie lactée.": { en: "A dark sky strewn with stars, crossed by the Milky Way.", zh: "繁星点点的夜空，银河横贯其间。" },
    "Chemin sous les arbres": { en: "Path beneath the trees", zh: "林荫小路" },
    "Un chemin de terre bordé d'arbres, un jour d'été à Moyemont.": { en: "A tree-lined dirt road on a summer day in Moyemont.", zh: "夏日的莫耶蒙，一条绿树成荫的土路。" },
    "Train à quai": { en: "Train at the platform", zh: "停靠站台的列车" },
    "Un train en gare vu d'en haut, en noir et blanc.": { en: "A train in the station seen from above, in black and white.", zh: "俯瞰车站里的列车，黑白影像。" },
    "Le phare du Loup": { en: "Le Loup lighthouse", zh: "Le Loup 灯塔" },
    "Un phare solitaire dans une mer de brume.": { en: "A lone lighthouse in a sea of mist.", zh: "雾海中孤独的灯塔。" },
    "Rose": { zh: "玫瑰" },
    "La délicatesse des pétales d'une rose, en gros plan.": { en: "The delicate petals of a rose, up close.", zh: "玫瑰花瓣的细腻特写。" },
    "Notre-Dame de Niort": { en: "Notre-Dame, Niort", zh: "尼奥尔圣母院" },
    "Les flèches gothiques de l'église Notre-Dame au-dessus des toits de Niort.": { en: "The Gothic spires of Notre-Dame church above the rooftops of Niort.", zh: "尼奥尔屋顶之上，圣母院教堂的哥特式尖塔。" },
    "Les jardins de Villandry": { en: "The gardens of Villandry", zh: "维朗德里城堡花园" },
    "Les parterres du château de Villandry, vus du ciel.": { en: "The parterres of the Château de Villandry, seen from the sky.", zh: "从空中俯瞰维朗德里城堡的花坛。" },

    // Sélection du site photo (titres courts de vitrine/selection.txt)
    "Voie lactée": { en: "Milky Way", zh: "银河" },
    "Hôtel de ville de Cognac": { en: "Cognac town hall", zh: "干邑市政厅" },
    "Chemin sous les arbres, Moyemont": { en: "Path beneath the trees, Moyemont", zh: "莫耶蒙的林荫小路" },
    "Portrait en lumière naturelle": { en: "Portrait in natural light", zh: "自然光人像" },
    "Phare du Loup dans la brume": { en: "Le Loup lighthouse in the mist", zh: "雾中的 Le Loup 灯塔" },
    "Rose en gros plan": { en: "Rose, close up", zh: "玫瑰特写" },
    "Gare vue d'en haut, noir et blanc": { en: "Station from above, black and white", zh: "俯瞰车站，黑白" },
    "Jardins de Villandry": { en: "Villandry gardens", zh: "维朗德里花园" },
    "Moineau sur une pierre": { en: "Sparrow on a stone", zh: "石头上的麻雀" },
    "Vagues bleues": { en: "Blue waves", zh: "蓝色波浪" },
    "Abbaye du Mont-Saint-Michel": { en: "Mont-Saint-Michel Abbey", zh: "圣米歇尔山修道院" },
    "Prairie fleurie": { en: "Flower meadow", zh: "繁花草地" },
    "Façade à Angoulême": { en: "Façade in Angoulême", zh: "昂古莱姆的建筑立面" },
    "Goéland sur un muret": { en: "Gull on a low wall", zh: "矮墙上的海鸥" },
    "Tour de bureaux à Paris": { en: "Office tower in Paris", zh: "巴黎的办公大楼" },
    "Banc en automne": { en: "Bench in autumn", zh: "秋日长椅" },
    "Phare de Granville": { en: "Granville lighthouse", zh: "格朗维尔灯塔" },
    "Alliances de mariage": { en: "Wedding rings", zh: "婚戒" },
    "Rue de Poitiers": { en: "Street in Poitiers", zh: "普瓦捷街景" },
    "Barque et feuilles mortes, noir et blanc": { en: "Rowboat and fallen leaves, black and white", zh: "小船与落叶，黑白" },
    "Chaos de rochers sur la côte": { en: "Jumble of rocks on the coast", zh: "海岸乱石" },
    "Église de Buzy, Pyrénées": { en: "Church of Buzy, Pyrenees", zh: "比利牛斯山区的比兹教堂" },

    // Séries et galeries du site photo
    "Séries et galeries": { en: "Series and galleries", zh: "系列与图集" },
    "Des centaines de photographies libres de droits, racontées en séries et rangées en galeries, à télécharger gratuitement sur Pexels.": { en: "Hundreds of royalty-free photographs, told in series and arranged in galleries, free to download on Pexels.", zh: "数百张免版税照片，以系列讲述、按图集分类，可在 Pexels 免费下载。" },
    "Par lieu": { en: "By place", zh: "按地点" },
    "Toutes les galeries": { en: "All galleries", zh: "全部图集" },
    "Le site photo": { en: "The photo site", zh: "摄影网站" },
    "Éclipse totale de Soleil en Galice": { en: "Total solar eclipse in Galicia", zh: "加利西亚日全食" },
    "Galice, Espagne": { en: "Galicia, Spain", zh: "西班牙加利西亚" },
    "12 août 2026": { en: "12 August 2026", zh: "2026年8月12日" },
    "Villandry, Centre-Val de Loire": { zh: "中央-卢瓦尔河谷大区维朗德里" },
    "Été 2026": { en: "Summer 2026", zh: "2026年夏" },
    "L'Universidad Laboral de Gijón": { en: "The Universidad Laboral of Gijón", zh: "希洪劳动大学" },
    "Gijón, Asturies, Espagne": { en: "Gijón, Asturias, Spain", zh: "西班牙阿斯图里亚斯希洪" },
    "La côte des Cathédrales, à Ribadeo": { en: "The Cathedrals Beach, Ribadeo", zh: "里瓦德奥的大教堂海滩" },
    "Ribadeo, Galice, Espagne": { en: "Ribadeo, Galicia, Spain", zh: "西班牙加利西亚里瓦德奥" },
    "Le chemin de Saint-Jacques en Béarn": { en: "The Way of St James in Béarn", zh: "贝阿恩的圣雅各之路" },
    "Béarn, Pyrénées-Atlantiques": { zh: "大西洋比利牛斯省贝阿恩" },
    "Au pied du Pic du Midi d'Ossau": { en: "At the foot of the Pic du Midi d’Ossau", zh: "奥索南峰脚下" },
    "Vallée d'Ossau, Béarn": { en: "Ossau Valley, Béarn", zh: "贝阿恩奥索河谷" },
    "Nuits étoilées": { en: "Starry nights", zh: "星夜" },
    "France et Espagne": { en: "France and Spain", zh: "法国与西班牙" },
    "2022 à 2026": { en: "2022 to 2026", zh: "2022年至2026年" },
    "Jardins des châteaux de la Loire": { en: "Loire château gardens", zh: "卢瓦尔河谷城堡花园" },
    "Ciel et astrophotographie": { en: "Sky and astrophotography", zh: "天空与天文摄影" },
    "Nuages et couchers de soleil": { en: "Clouds and sunsets", zh: "云彩与日落" },
    "Paysages et campagne": { en: "Landscapes and countryside", zh: "风景与乡村" },
    "Arbres et forêts": { en: "Trees and forests", zh: "树木与森林" },
    "Fleurs et macro": { en: "Flowers and macro", zh: "花卉与微距" },
    "Mer et littoral": { en: "Sea and coast", zh: "海洋与海岸" },
    "Rivières, lacs et canaux": { en: "Rivers, lakes and canals", zh: "河流、湖泊与运河" },
    "Architecture et patrimoine": { en: "Architecture and heritage", zh: "建筑与遗产" },
    "Églises et cathédrales": { en: "Churches and cathedrals", zh: "教堂与大教堂" },
    "Villes et scènes de rue": { en: "Cities and street scenes", zh: "城市与街景" },
    "Transports": { en: "Transport", zh: "交通" },
    "Portraits": { zh: "人像" },
    "Scènes de vie": { en: "Everyday life", zh: "生活场景" },
    "Mariage": { en: "Weddings", zh: "婚礼" },
    "Manifestations et engagement": { en: "Protests and activism", zh: "游行与社会参与" },
    "Animaux": { en: "Animals", zh: "动物" },
    "Cuisine et boissons": { en: "Food and drink", zh: "美食与饮品" },
    "Objets et natures mortes": { en: "Objects and still lifes", zh: "物品与静物" },
    "Noir et blanc": { en: "Black and white", zh: "黑白" },
    "Fonds abstraits": { en: "Abstract backgrounds", zh: "抽象背景" },
    "Pays basque": { en: "Basque Country", zh: "巴斯克地区" },
    "Asturies": { en: "Asturias", zh: "阿斯图里亚斯" },
    "Galice": { en: "Galicia", zh: "加利西亚" },
    "Chemin de Saint-Jacques": { en: "Way of St James", zh: "圣雅各之路" },
    "Pyrénées": { en: "Pyrenees", zh: "比利牛斯山" },
    "Bordeaux": { zh: "波尔多" },
    "Niort et le Poitou": { en: "Niort and Poitou", zh: "尼奥尔与普瓦图" },
    "Val de Loire": { en: "Loire Valley", zh: "卢瓦尔河谷" },
    "Charente : Cognac et Angoulême": { en: "Charente: Cognac and Angoulême", zh: "夏朗德：干邑与昂古莱姆" },
    "Paris": { zh: "巴黎" },
    "Normandie et Bretagne": { en: "Normandy and Brittany", zh: "诺曼底与布列塔尼" },
    "Vosges, Lorraine et Alsace": { en: "Vosges, Lorraine and Alsace", zh: "孚日、洛林与阿尔萨斯" },

    // Livres
    "LIVRES": { en: "BOOKS", zh: "书籍" },
    "Publications": { zh: "出版作品" },
    "Découvrez mes ouvrages, fruits de passion et de réflexion.": { en: "Discover my books, born of passion and reflection.", zh: "探索我的作品，热情与思考的结晶。" },
    "Couverture de Darshan": { en: "Cover of Darshan", zh: "《Darshan》封面" },
    "Roman": { en: "Novel · in French", zh: "小说 · 法语" },
    "La SEP, collection Cheminement": { en: "SEP, Cheminement collection", zh: "普瓦图出版社 · Cheminement 丛书" },
    "Une exploration poétique des émotions humaines à travers le prisme de l'écriture contemporaine.": { en: "A poetic exploration of human emotions through the lens of contemporary writing.", zh: "以当代写作的视角，诗意地探索人类的情感。" },
    "Couverture de L'histoire du petit Théo": { en: "Cover of L’histoire du petit Théo", zh: "《小泰奥的故事》封面" },
    "L'histoire du petit Théo": { en: "L’histoire du petit Théo (The Story of Little Théo)", zh: "《小泰奥的故事》" },
    "Conte": { en: "Tale · in French", zh: "童话 · 法语" },
    "Un conte touchant qui explore l'imagination et les rêves d'enfance avec tendresse.": { en: "A touching tale that tenderly explores imagination and childhood dreams.", zh: "一个动人的故事，温柔地探索想象力与童年的梦想。" },
    "Écriture": { en: "Writing", zh: "写作" },
    "Romans": { en: "Novels", zh: "小说" },
    "Contes": { en: "Tales", zh: "童话" },
    "Édition": { en: "Publishing", zh: "出版" },

    // Mémoire
    "Recherche académique": { en: "Academic research", zh: "学术研究" },
    "Quelle influence la médiation auctoriale exerce-t-elle sur le public d’un site d’auteur ? Pour y répondre, ce mémoire de master 2 Livres et médiations s’appuie sur un questionnaire rempli par 102 visiteurs de sites d’auteurs et sur des entretiens avec des acteurs de leur création.": { en: "How does authorial mediation influence the audience of an author’s website? To answer this question, this master’s thesis in Books and Mediation draws on a questionnaire completed by 102 visitors to author websites and on interviews with people involved in creating them.", zh: "作者媒介如何影响作者网站的受众？为回答这一问题，这篇“书籍与媒介”硕士论文基于 102 位作者网站访客填写的问卷，以及对网站创建相关人士的访谈。" },
    "Sujet": { en: "Subject", zh: "主题" },
    "L’influence de la médiation auctoriale du site d’auteur": { en: "The influence of authorial mediation through the author’s website", zh: "作者网站中作者媒介的影响" },
    "Institution": { zh: "机构" },
    "Université de Poitiers": { en: "University of Poitiers", zh: "普瓦捷大学" },
    "Année": { en: "Year", zh: "年份" },
    "Juin 2023": { en: "June 2023", zh: "2023年6月" },
    "Consulter le mémoire": { en: "Read the thesis (in French)", zh: "阅读论文（法语）" },
    "L'écriture est l'art de donner forme à l'invisible.": { en: "Writing is the art of giving shape to the invisible.", zh: "写作，是赋予无形以形态的艺术。" },

    // Extraits
    "Extraits": { en: "Excerpts", zh: "节选" },
    "Plongez dans mes écrits": { en: "Dive into my writing", zh: "走进我的文字" },
    "Des étincelles passent et se chassent sur une toile d’un bleu royal. Il est d’un régal sans pareil d’admirer ce que nous offre l’éternel. L’infini s’y déploie, s’exempte de toute loi.": { en: "Sparks pass and chase one another across a canvas of royal blue. There is no delight like admiring what eternity offers us. Infinity unfolds there, free of every law.", zh: "火花在宝蓝色的画布上掠过、追逐。欣赏永恒赐予我们的一切，是无与伦比的享受。无限在那里铺展，不受任何法则约束。" },
    "Notre regard va s’attarder sur le petit Théo. Non pas qu’il soit plus exceptionnel qu’un autre enfant à un quelconque égard, mais cet enfant présente, il faut le dire, un sourire charmeur, les yeux de l’océan et un rire enjôleur.": { en: "Our gaze will linger on little Théo. Not that he is in any way more exceptional than any other child, but this child has, it must be said, a charming smile, eyes like the ocean and a winning laugh.", zh: "我们的目光将停留在小泰奥身上。倒不是说他在哪方面比别的孩子更特别，但必须承认，这个孩子有着迷人的微笑、海洋般的眼睛和讨人喜欢的笑声。" },
    "Dans sa visée paratextuelle, le site d’auteur devient un musée pour l’écrivain. Cet espace d’archive permet de rassembler des extraits d’œuvres, des préfaces, des postfaces, des notes de l’auteur ou encore des photographies.": { en: "In its paratextual aim, the author’s website becomes a museum for the writer. This archival space brings together excerpts from works, prefaces, afterwords, the author’s notes and even photographs.", zh: "从副文本的角度看，作者网站成为作家的博物馆。这一档案空间汇集了作品节选、序言、后记、作者笔记乃至照片。" },
    "Mémoire": { en: "Thesis", zh: "论文" },
    "Mémoire de recherche": { en: "Research thesis", zh: "研究论文" },
    "Travail académique": { en: "Academic work · in French", zh: "学术论文 · 法语" },

    // Contact et pied de page
    "Écrivez-moi": { en: "Write to me", zh: "给我写信" },
    "Une question sur mes livres, mes photos ou mes créations ? N’hésitez pas à m’écrire.": { en: "A question about my books, photos or creations? Feel free to write to me.", zh: "对我的书、照片或作品有疑问？欢迎来信。" },
    "Email": { zh: "电子邮件" },
    "Photos libres de droits": { en: "Royalty-free photos", zh: "免版税照片" },
    "Mentions légales": { en: "Legal notice (in French)", zh: "法律声明（法语）" },
    "© 2026 Karl Forterre. Tous droits réservés.": { en: "© 2026 Karl Forterre. All rights reserved.", zh: "© 2026 Karl Forterre。保留所有权利。" }
};
